/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DAO.AlocacoesDAO;
import classes.Alocacoes;
import java.text.SimpleDateFormat;
import java.util.Random;
import javax.swing.DefaultComboBoxModel;

/**
 *
 * @author 886918
 */
public class ViewNovaAlocacao extends javax.swing.JFrame {
    
    public void readCbbCursos(){
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cbbCurso.getModel();
        AlocacoesDAO adao = new AlocacoesDAO();
        for (Alocacoes a  : adao.readCourses()) {
            modelo.addElement(
                a.getCurso()
            );
    
        }
    }
    public void readCbbDocentes(){
        DefaultComboBoxModel modelo = (DefaultComboBoxModel) cbbDocente.getModel();
        AlocacoesDAO adao = new AlocacoesDAO();
        for (Alocacoes a  : adao.readTeachers()) {
            modelo.addElement(
                a.getDocente()
            );
    
        }
    }
    
    
    /**
     * Creates new form NewAlocation
     */
    public ViewNovaAlocacao() {
        initComponents();
        readCbbCursos();
        readCbbDocentes();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel4 = new javax.swing.JLabel();
        jComboBox3 = new javax.swing.JComboBox<>();
        jPopupMenu1 = new javax.swing.JPopupMenu();
        jPopupMenu2 = new javax.swing.JPopupMenu();
        jPopupMenu3 = new javax.swing.JPopupMenu();
        btnAlocar = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        cbbCurso = new javax.swing.JComboBox<>();
        cbbSala = new javax.swing.JComboBox<>();
        cbbDocente = new javax.swing.JComboBox<>();
        jLabel6 = new javax.swing.JLabel();
        btnVoltar = new javax.swing.JButton();
        jLabel7 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        btnNoite = new javax.swing.JRadioButton();
        btnManha = new javax.swing.JRadioButton();
        btnTarde = new javax.swing.JRadioButton();
        jdtData = new com.toedter.calendar.JDateChooser();

        jLabel4.setText("Andar:");

        jComboBox3.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setAlwaysOnTop(true);
        setResizable(false);

        btnAlocar.setText("Alocar");
        btnAlocar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAlocarActionPerformed(evt);
            }
        });

        jLabel1.setText("Sala:");

        jLabel2.setText("Curso:");

        jLabel5.setText("Docente:");

        cbbSala.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {
            "1 - Salão escolar",
            "2 - Laboratório de estética",
            "3 - Imagem pessoal",
            "4 - Informática",
            "5 - Auditório",
            "101 - Informática",
            "102 - Sala convencional",
            "103 - Sala convencional",
            "104 - Sala convencional",
            "105 - Laboratório de estética",
            "106 - Informática",
            "201 - Sala convencional",
            "202 - Sala convencional",
            "203 - Laboratório de estética",
            "204 - Laboratório de estética",
            "205 - Sala convencional",
            "206 - Sala convencional",
            "207 - Laboratório de Enfermagem",}));
cbbSala.addActionListener(new java.awt.event.ActionListener() {
    public void actionPerformed(java.awt.event.ActionEvent evt) {
        cbbSalaActionPerformed(evt);
    }
    });

    cbbDocente.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            cbbDocenteActionPerformed(evt);
        }
    });

    jLabel6.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
    jLabel6.setText("Nova alocação");

    btnVoltar.setText("Voltar");
    btnVoltar.addActionListener(new java.awt.event.ActionListener() {
        public void actionPerformed(java.awt.event.ActionEvent evt) {
            btnVoltarActionPerformed(evt);
        }
    });

    jLabel7.setText("Turno:");

    jLabel8.setText("Data:");

    btnNoite.setText("Noite");

    btnManha.setText("Manhã");

    btnTarde.setText("Tarde");

    javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
    getContentPane().setLayout(layout);
    layout.setHorizontalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createSequentialGroup()
                    .addContainerGap()
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(layout.createSequentialGroup()
                            .addGap(9, 9, 9)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel8)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(jdtData, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGroup(layout.createSequentialGroup()
                                    .addComponent(jLabel1)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(cbbSala, javax.swing.GroupLayout.PREFERRED_SIZE, 251, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(66, 66, 66)
                                    .addComponent(jLabel2))
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(60, 60, 60)
                                    .addComponent(jLabel5)))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(cbbCurso, 0, 409, Short.MAX_VALUE)
                                .addComponent(cbbDocente, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGroup(layout.createSequentialGroup()
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(jLabel6)
                                .addGroup(layout.createSequentialGroup()
                                    .addGap(6, 6, 6)
                                    .addComponent(jLabel7)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                    .addComponent(btnManha)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnTarde)
                                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                    .addComponent(btnNoite)))
                            .addGap(0, 0, Short.MAX_VALUE))))
                .addGroup(layout.createSequentialGroup()
                    .addGap(278, 278, 278)
                    .addComponent(btnAlocar)
                    .addGap(73, 73, 73)
                    .addComponent(btnVoltar)))
            .addGap(15, 15, 15))
    );
    layout.setVerticalGroup(
        layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
        .addGroup(layout.createSequentialGroup()
            .addContainerGap()
            .addComponent(jLabel6)
            .addGap(30, 30, 30)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel1)
                .addComponent(cbbSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(jLabel5)
                .addComponent(cbbDocente, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(cbbCurso, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel2))
                    .addGroup(layout.createSequentialGroup()
                        .addComponent(jLabel8)
                        .addGap(6, 6, 6)))
                .addComponent(jdtData, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                .addComponent(jLabel7)
                .addComponent(btnManha)
                .addComponent(btnTarde)
                .addComponent(btnNoite))
            .addGap(22, 22, 22)
            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addComponent(btnVoltar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addComponent(btnAlocar, javax.swing.GroupLayout.PREFERRED_SIZE, 22, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addContainerGap(16, Short.MAX_VALUE))
    );

    pack();
    setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnAlocarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAlocarActionPerformed
        // TODO add your handling code here:
        Alocacoes a = new Alocacoes();
        AlocacoesDAO adao = new AlocacoesDAO();
       
        if (btnManha.isSelected()) {
            a.setTurnoManha(true);
        }
        if (btnTarde.isSelected()) {
            a.setTurnoTarde(true);
        }
        if (btnNoite.isSelected()) {
            a.setTurnoNoite(true);
        }
        a.setCurso(cbbCurso.getSelectedItem().toString());
        a.setDocente(cbbDocente.getSelectedItem().toString());
        a.setSala(cbbSala.getSelectedItem().toString());
        a.setData(jdtData.getDate());
        a.definirTurno();
        int r = new Random().nextInt(1000, 9999);
        a.setId(r);
        adao.create(a);
        
        btnManha.setSelected(false);
        btnTarde.setSelected(false);
        btnNoite.setSelected(false);
        jdtData.cleanup();
        
    }//GEN-LAST:event_btnAlocarActionPerformed

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        ViewAlocacoes alocacoes = new ViewAlocacoes();
        alocacoes.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void cbbSalaActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbSalaActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbSalaActionPerformed

    private void cbbDocenteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbbDocenteActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbbDocenteActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewNovaAlocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewNovaAlocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewNovaAlocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewNovaAlocacao.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewNovaAlocacao().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAlocar;
    private javax.swing.JRadioButton btnManha;
    private javax.swing.JRadioButton btnNoite;
    private javax.swing.JRadioButton btnTarde;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JComboBox<String> cbbCurso;
    private javax.swing.JComboBox<String> cbbDocente;
    private javax.swing.JComboBox<String> cbbSala;
    private javax.swing.JComboBox<String> jComboBox3;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JPopupMenu jPopupMenu1;
    private javax.swing.JPopupMenu jPopupMenu2;
    private javax.swing.JPopupMenu jPopupMenu3;
    private com.toedter.calendar.JDateChooser jdtData;
    // End of variables declaration//GEN-END:variables
}
