/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package view;

import DAO.CursosDAO;
import classes.Cursos;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author 886918
 */
public class ViewCursos extends javax.swing.JFrame {

    
  
    /**
     * Creates new form ViewCourses
     */
    //CONSTRUTOR
    public ViewCursos() {
        initComponents();
        readJTable();
    }
    
    
     public void readJTable(){
       DefaultTableModel modelo = (DefaultTableModel) jtbTabelaCursos.getModel();
       modelo.setNumRows(0);
       btnAtualizar.setEnabled(false);
       CursosDAO cdao = new CursosDAO();
       
       for(Cursos c: cdao.read()){
           modelo.addRow(new Object[]{
               c.getNome(),
               c.getTipoDeSala(),
               c.getDiasRealizados(),
               c.getTurno(),
               c.getCodigoCurso()
           });
       }
        }
    
    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel1 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        jLabel6 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jTextField1 = new javax.swing.JTextField();
        jButton2 = new javax.swing.JButton();
        btnVoltar1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox1 = new javax.swing.JCheckBox();
        list1 = new java.awt.List();
        btnVoltar = new javax.swing.JButton();
        jScrollPane2 = new javax.swing.JScrollPane();
        jtbTabelaCursos = new javax.swing.JTable();
        jLabel4 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        cbbTipoDeSala = new javax.swing.JComboBox<>();
        txtNome = new javax.swing.JTextField();
        btnNovoCurso = new javax.swing.JButton();
        btnExcluir = new javax.swing.JButton();
        jLabel11 = new javax.swing.JLabel();
        btnManha = new javax.swing.JRadioButton();
        btnNoite = new javax.swing.JRadioButton();
        btnTarde = new javax.swing.JRadioButton();
        filler1 = new javax.swing.Box.Filler(new java.awt.Dimension(0, 0), new java.awt.Dimension(0, 0), new java.awt.Dimension(32767, 32767));
        btnAtualizar = new javax.swing.JButton();
        spnCod = new javax.swing.JSpinner();
        canvas1 = new java.awt.Canvas();
        jLabel12 = new javax.swing.JLabel();
        btnSeg = new javax.swing.JRadioButton();
        btnSex = new javax.swing.JRadioButton();
        btnSab = new javax.swing.JRadioButton();
        btnTer = new javax.swing.JRadioButton();
        btnQui = new javax.swing.JRadioButton();
        btnQua = new javax.swing.JRadioButton();

        jCheckBox3.setText("Noite");

        jLabel1.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel1.setText("Novo curso");

        jLabel5.setText("Código:");

        jLabel2.setText("Nome: ");

        jLabel6.setText("Tipo de sala:");

        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        jButton2.setText("Confirmar");

        btnVoltar1.setText("Voltar");
        btnVoltar1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltar1ActionPerformed(evt);
            }
        });

        jLabel3.setText("Turno:");

        jCheckBox2.setText("Manhã");

        jCheckBox1.setText("Tarde");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setResizable(false);

        btnVoltar.setText("Voltar");
        btnVoltar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnVoltarActionPerformed(evt);
            }
        });

        jtbTabelaCursos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Nome", "Tipo de sala", "Dias realizados", "Turno", "Código"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jtbTabelaCursos.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jtbTabelaCursosMouseClicked(evt);
            }
        });
        jScrollPane2.setViewportView(jtbTabelaCursos);
        if (jtbTabelaCursos.getColumnModel().getColumnCount() > 0) {
            jtbTabelaCursos.getColumnModel().getColumn(0).setResizable(false);
            jtbTabelaCursos.getColumnModel().getColumn(0).setPreferredWidth(500);
            jtbTabelaCursos.getColumnModel().getColumn(1).setResizable(false);
            jtbTabelaCursos.getColumnModel().getColumn(1).setPreferredWidth(300);
            jtbTabelaCursos.getColumnModel().getColumn(2).setResizable(false);
            jtbTabelaCursos.getColumnModel().getColumn(2).setPreferredWidth(200);
            jtbTabelaCursos.getColumnModel().getColumn(3).setResizable(false);
            jtbTabelaCursos.getColumnModel().getColumn(3).setPreferredWidth(150);
            jtbTabelaCursos.getColumnModel().getColumn(4).setResizable(false);
            jtbTabelaCursos.getColumnModel().getColumn(4).setPreferredWidth(100);
        }

        jLabel4.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        jLabel4.setText("Cursos");

        jLabel8.setText("Código:");

        jLabel9.setText("Nome: ");

        jLabel10.setText("Tipo de sala:");

        cbbTipoDeSala.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] {
            "Salão escolar",
            "Laboratório de estética",
            "Imagem pessoal",
            "Auditório",
            "Informática",
            "Sala convencional",
            "Laboratório de Enfermagem",
        }));

        btnNovoCurso.setText("Cadastrar");
        btnNovoCurso.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNovoCursoActionPerformed(evt);
            }
        });

        btnExcluir.setText("Excluir");
        btnExcluir.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnExcluirActionPerformed(evt);
            }
        });

        jLabel11.setText("Turno:");

        btnManha.setText("Manhã");

        btnNoite.setText("Noite");

        btnTarde.setText("Tarde");

        btnAtualizar.setText("Atualizar");
        btnAtualizar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAtualizarActionPerformed(evt);
            }
        });

        spnCod.setFont(new java.awt.Font("Segoe UI", 0, 18)); // NOI18N
        spnCod.setModel(new javax.swing.SpinnerNumberModel(0, 0, 999, 1));

        jLabel12.setText("Dias realizados:");

        btnSeg.setText("Seg");

        btnSex.setText("Sex");

        btnSab.setText("Sab");

        btnTer.setText("Ter");

        btnQui.setText("Qui");

        btnQua.setText("Qua");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(btnVoltar))
                    .addGroup(layout.createSequentialGroup()
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE)
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel11)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel4)
                                        .addGap(242, 242, 242)
                                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                .addGap(0, 690, Short.MAX_VALUE))
                            .addGroup(layout.createSequentialGroup()
                                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(canvas1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGroup(layout.createSequentialGroup()
                                        .addComponent(jLabel9)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addGap(18, 18, 18)
                                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(jLabel10)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(cbbTipoDeSala, javax.swing.GroupLayout.PREFERRED_SIZE, 259, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addGroup(layout.createSequentialGroup()
                                                .addComponent(btnSeg)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnTer)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnQua)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnQui)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnSex)
                                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                                .addComponent(btnSab))
                                            .addComponent(jLabel12))
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(jLabel8)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                        .addComponent(spnCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 13, Short.MAX_VALUE)))
                                .addGap(187, 187, 187))
                            .addGroup(layout.createSequentialGroup()
                                .addComponent(btnManha)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnTarde)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                                .addComponent(btnNoite)
                                .addGap(181, 181, 181)
                                .addComponent(btnNovoCurso)
                                .addGap(18, 18, 18)
                                .addComponent(btnAtualizar, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(btnExcluir, javax.swing.GroupLayout.PREFERRED_SIZE, 80, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(0, 355, Short.MAX_VALUE)))
                        .addContainerGap())))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(jLabel4)
                        .addGap(0, 0, 0)
                        .addComponent(canvas1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(12, 12, 12)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(txtNome, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(cbbTipoDeSala, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel9)
                            .addComponent(jLabel10)
                            .addComponent(jLabel8)
                            .addComponent(spnCod, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel11)
                            .addComponent(jLabel12))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnSeg)
                                .addComponent(btnQua)
                                .addComponent(btnTer)
                                .addComponent(btnSex)
                                .addComponent(btnQui)
                                .addComponent(btnSab))
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnManha)
                                .addComponent(btnNoite)
                                .addComponent(btnTarde)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(filler1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(layout.createSequentialGroup()
                        .addGap(91, 165, Short.MAX_VALUE)
                        .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(btnNovoCurso, javax.swing.GroupLayout.Alignment.TRAILING)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(btnExcluir)
                                .addComponent(btnAtualizar)))
                        .addGap(18, 18, 18)
                        .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 400, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(18, 18, 18)
                        .addComponent(btnVoltar)))
                .addContainerGap())
        );

        pack();
        setLocationRelativeTo(null);
    }// </editor-fold>//GEN-END:initComponents

    private void btnVoltarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltarActionPerformed
        // TODO add your handling code here:
        ViewMenu menu = new ViewMenu();
        dispose();
        menu.setVisible(true);
    }//GEN-LAST:event_btnVoltarActionPerformed

    private void btnVoltar1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnVoltar1ActionPerformed
        // TODO add your handling code here:
        ViewCursos cursos = new ViewCursos();
        cursos.setVisible(true);
        dispose();
    }//GEN-LAST:event_btnVoltar1ActionPerformed

    private void btnExcluirActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnExcluirActionPerformed
        // TODO add your handling code here:
        if(jtbTabelaCursos.getSelectedRow() != 1 ){
        Cursos c = new Cursos();
        CursosDAO dao = new CursosDAO();
        c.setCodigoCurso((int)jtbTabelaCursos.getValueAt(jtbTabelaCursos.getSelectedRow(), 4));
        dao.delete(c);
        txtNome.setText("");
        spnCod.setValue(0);
        btnManha.setSelected(false);
        btnTarde.setSelected(false);
        btnNoite.setSelected(false);
        readJTable();
    }     
    }//GEN-LAST:event_btnExcluirActionPerformed

    private void btnNovoCursoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNovoCursoActionPerformed
        // TODO add your handling code here:
        CursosDAO cdao = new CursosDAO();
        Cursos c = new Cursos();
        if (btnManha.isSelected()) {
            c.setTurnoManha(true);
        }
        if (btnTarde.isSelected()) {
            c.setTurnoTarde(true);
        }
        if (btnNoite.isSelected()) {
            c.setTurnoNoite(true);
        }
        if (btnSeg.isSelected()) {
            c.setDiaSeg(true);
        }
        if (btnTer.isSelected()) {
            c.setDiaTer(true);
        }
        if (btnQua.isSelected()) {
            c.setDiaQua(true);
        }
        if (btnQui.isSelected()) {
            c.setDiaQui(true);
        }
        if (btnSex.isSelected()) {
            c.setDiaSex(true);
        }
        if (btnSab.isSelected()) {
            c.setDiaSab(true);
        }
        c.setNome(txtNome.getText());
        c.setCodigoCurso(Integer.parseInt(spnCod.getValue().toString()));
        c.setTipoDeSala(cbbTipoDeSala.getSelectedItem().toString());
        c.definirTurno();
        c.definirDias();
        if (((int)spnCod.getValue()) > 0) {
        cdao.create(c);
        readJTable();
        }else{
            JOptionPane.showMessageDialog(null, "Código inválido!");
        }
        txtNome.setText("");
        spnCod.setValue(0);
        btnManha.setSelected(false);
        btnTarde.setSelected(false);
        btnNoite.setSelected(false);
        btnSeg.setSelected(false);
        btnTer.setSelected(false);
        btnQua.setSelected(false);
        btnQui.setSelected(false);
        btnSex.setSelected(false);
        btnSab.setSelected(false);      
        
        
    }//GEN-LAST:event_btnNovoCursoActionPerformed

    private void jtbTabelaCursosMouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jtbTabelaCursosMouseClicked
        // TODO add your handling code here:
        if (jtbTabelaCursos.getSelectedRow() != -1) {
            btnSeg.setSelected(false);
            btnTer.setSelected(false);
            btnQua.setSelected(false);
            btnQui.setSelected(false);
            btnSex.setSelected(false);
            btnSab.setSelected(false);
            btnAtualizar.setEnabled(true);
            btnManha.setSelected(false);
            btnTarde.setSelected(false);
            btnNoite.setSelected(false);
            txtNome.setText(jtbTabelaCursos.getValueAt(jtbTabelaCursos.getSelectedRow(), 0).toString());
            spnCod.setValue(jtbTabelaCursos.getValueAt(jtbTabelaCursos.getSelectedRow(), 4));
            String turno = jtbTabelaCursos.getValueAt(jtbTabelaCursos.getSelectedRow(),3).toString();
            for (int i = 0; i < turno.length(); i++) {
                char x = turno.charAt(i);
                if (x == 'M') {
                    btnManha.setSelected(true);
                }
                if (x == 'T') {
                    btnTarde.setSelected(true);
                }
                if (x == 'N') {
                    btnNoite.setSelected(true);
                }
            }
            String diasRealizados = jtbTabelaCursos.getValueAt(jtbTabelaCursos.getSelectedRow(), 2).toString();
                if (diasRealizados.contains("Seg")) {
                    btnSeg.setSelected(true);
                }
                if (diasRealizados.contains("Ter")) {
                    btnTer.setSelected(true);
                }
                if (diasRealizados.contains("Qua")) {
                    btnQua.setSelected(true);
                }
                if (diasRealizados.contains("Qui")) {
                    btnQui.setSelected(true);
                }
                if (diasRealizados.contains("Sex")) {
                    btnSex.setSelected(true);
                }
                if (diasRealizados.contains("Sab")) {
                    btnSab.setSelected(true);
                }        
        }
 
       
    }//GEN-LAST:event_jtbTabelaCursosMouseClicked

    private void btnAtualizarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAtualizarActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnAtualizarActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ViewCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ViewCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ViewCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ViewCursos.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ViewCursos().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnAtualizar;
    private javax.swing.JButton btnExcluir;
    private javax.swing.JRadioButton btnManha;
    private javax.swing.JRadioButton btnNoite;
    private javax.swing.JButton btnNovoCurso;
    private javax.swing.JRadioButton btnQua;
    private javax.swing.JRadioButton btnQui;
    private javax.swing.JRadioButton btnSab;
    private javax.swing.JRadioButton btnSeg;
    private javax.swing.JRadioButton btnSex;
    private javax.swing.JRadioButton btnTarde;
    private javax.swing.JRadioButton btnTer;
    private javax.swing.JButton btnVoltar;
    private javax.swing.JButton btnVoltar1;
    private java.awt.Canvas canvas1;
    private javax.swing.JComboBox<String> cbbTipoDeSala;
    private javax.swing.Box.Filler filler1;
    private javax.swing.JButton jButton2;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JTable jtbTabelaCursos;
    private java.awt.List list1;
    private javax.swing.JSpinner spnCod;
    private javax.swing.JTextField txtNome;
    // End of variables declaration//GEN-END:variables
}
